# Generated by Django 4.2.2 on 2023-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_quiz_description_remove_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
